version: "3"

services:

  php:
    build: .
    ports:
      - "3000:80"
      - "443:433"
    volumes:
      - ./:/var/www/html
    links:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: upinside
    volumes:
      - ./.docker/arquivosbancodados:/var/lib/postgresql/data